#coding = utf-8
from selenium import webdriver
import time
browser = webdriver.Chrome()
browser.maximize_window()
browser.get("http://www.baidu.com")
time.sleep(2)
# browser.find_element_by_id("kw").send_keys("阿里巴巴")
# # time.sleep(2)
# # browser.find_element_by_id("su").click()
# # time.sleep(2)
# browser.find_element_by_name("wd").send_keys("baidu")
# time.sleep(2)
# browser.find_element_by_id("su").click()
# time.sleep(2)
# browser.find_element_by_class_name("s_ipt").send_keys("腾讯")
# time.sleep(2)
# browser.find_element_by_id("su").click()
# time.sleep(2)
# browser.find_element_by_link_text("新闻").click()
# time.sleep(2)
# browser.find_element_by_partial_link_text("hao").click()
# time.sleep(5)
#//*[@id="kw"]
# browser.find_element_by_xpath("//*[@id=\"kw\"]").send_keys("字节跳动")
# time.sleep(3)
# browser.find_element_by_xpath("//*[@id='su']").submit()
# browser.implicitly_wait(10)
# browser.find_element_by_link_text("地图").click()
# browser.find_element_by_css_selector("#kw").send_keys("huawei")
# time.sleep(3)
# browser.find_element_by_css_selector("#su").click()
# time.sleep(3)
# text = browser.find_element_by_id("bottom_layer").text
# print (text)
print(browser.title)
print(browser.current_url)
browser.quit()